### ISSUE TITLE
Subscript out of bound

### ISSUE THREAD

**Issue by Awruger321** [CSAFE-ISU/handwriter#137]
When creating a clustering template the following error occurs after 'start making a dataframe of number of graphs with various numbers of loops and edges...'
Error in template_proc_list[[i]] : subscript out of bound

Is there an option to solve this error?

**Comment by stephaniereinders** [comment]
I wasn't able to reproduce the error, but it might be a result of a bug that I unintentionally introduced when I updated process_batch_list() in early March. That bug has been fixed. Try installing the latest development version of handwriter from GitHub with
```
devtools::install_github("CSAFE-ISU/handwriter")
```
Then try running `make_clustering_templates()`. If you want to create a template with K=40 clusters, you should use 100 template training documents. Otherwise, the algorithm won't have enough training data from which to choose 40 starting cluster centers. If you use fewer clusters, you don't need as many training documents.

Please let me know if you still encounter errors.
