### ISSUE TITLE
How do we troubleshoot installation issues?

### ISSUE THREAD

**Issue by stephaniereinders** [CSAFE-ISU/handwriter#22]
This morning both Allie and I ran `devtools::install_github("CSAFE-ISU/handwriter")` on our Macs and received the error

Downloading GitHub repo CSAFE-ISU/handwriter@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/CSAFE-ISU/handwriter/tarball/HEAD' failed

Increasing the timeout fixed the problem for me:
```
options(timeout=400)
devtools::install_github("CSAFE-ISU/handwriter")
```
Allie is still unable to install handwriter from GitHub. She now receives an error about not being able to find the directory for gfortran. After we figure out how to fix this, these "fixes" should be added to the documentation.

**Comment by ahgamut** [comment]
The gfortran issue has been "fixed" on Alexandra's computer, but there might be two possible causes for the error.

## `handwriter` needs `-lgfortran`, but
## R on MacOS is unable to provide the correct location for it.

If you looked at the error logs, the error was with `-L/usr/local/gfortran/lib -lgfortran` (`-lgfortran not found`). This is because R is unable to find where `libgfortran.a` or `libgfortran.dylib` was located. 

The solution is:

a. Open Terminal on MacOS
b. if you don't have `gcc` already type `brew install gcc`
c. find where `libgfortran.a` is located: 
  1. type `gcc --version` to see the major gcc version (if it says 11.2.1, you should remember 11)
  2. type `ls /usr/local/lib/gcc/11` and you should see `libgfortran.a` and `libgfortran.dylib`

d. create and/or open the file `~/.R/Makevars` in some editor and then add the following lines

```make
# this is a comment
# the below line tells R where libgfortran.a is
FLIBS = -L/usr/local/lib/gcc/11 -lgfortran

```

e. reinstall `handwriter` via RStudio. it \*should\* be okay.


## `handwriter` doesn't actually need `-lgfortran`

I haven't actually tested this, but my guess would that `handwriter` doesn't actually need the `-lgfortran` line (`handwriter` isn't using fortran anywhere directly, and if it is, then gfortran would be linked by R anyway).

The fix in this case would be to remove the `(FLIBS)` part in `src/Makevars` and/or `src/Makevars.win`.

**Comment by stephaniereinders** [comment]
After deleting (FLIBS) from src/Makevars I ran check on the package which returned a warning:

```
❯ checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... WARNING
    apparently using $(BLAS_LIBS) without following $(FLIBS) in ‘src/Makevars’
```

**Comment by ahgamut** [comment]
Huh that's weird, should be possible to have `$(BLAS_LIBS)` without `$(FLIBS)` right? 
Then again I don't expect `handwriter` to use BLAS outright anywhere... so maybe the `src/Makevars`need not have `$(BLAS_LIBS)` and `$(LAPACK_LIBS)` either.

Option a) `src/Makevars` need not have any of `$(BLAS_LIBS)`, `$(LAPACK_LIBS)`, `$(FLIBS)`
Option b) `src/Makevars` has to have all of `$(FLIBS)`, `$(BLAS_LIBS)`, `$(LAPACK_LIBS)`, for some unknown reason

Let's see which one is the case.
